### ISSUE TITLE
Cookie isn't set on redirects

### ISSUE THREAD

**Issue by sectroyer** [vladko312/SSTImap#11]
I will use PortSwigger's "Basic server-side template injection (code context)" task as an example but I have encountered same issue elsewhere.

SSTImap makes request:
```
POST /my-account/change-blog-post-author-display HTTP/2
Host: 0a70002e03773a3d81129428007b00eb.web-security-academy.net
User-Agent: Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Cookie: session=Sk45UsfrkQRg3siVdnHxV8uBhDFG20gJ
Content-Length: 205
Content-Type: application/x-www-form-urlencoded

blog-post-author-display=1%22%29%25%7D%7B%7B6546555976%7D%7D%7B%7B%27nN%27%7D%7D%7B%25+raw+%27nN%27.join%28%27DB%27%29+%25%7D%7B%7B%27DB%27%7D%7D%7B%7B9359880974%7D%7D&csrf=xGbHC88kaLt5KmNUTq7zw3wZ3fMDDAGx
```

It gets redirect:
```
HTTP/2 302 Found
Location: /my-account
X-Frame-Options: SAMEORIGIN
Content-Length: 0
```

It follows without cookie:
```
GET /my-account HTTP/2
Host: 0a70002e03773a3d81129428007b00eb.web-security-academy.net
User-Agent: Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
```

I understand this happens because cookies are treated "as headers" however if I don't want to inject cookie there should be an option to treat them as regular cookies instead.

**Comment by vladko312** [comment]
I will look into this. You added the cookie as a header?

**Comment by sectroyer** [comment]
Nope I've added it as cookie. However the code you inherited from tplmap does this:
```
    def _parse_cookies(self):
        # Just add cookies as headers, to avoid duplicating
        # the parsing code. Concatenate to avoid headers with
        # the same key.
        cookies = self.args.get('cookies', [])
        if cookies:
            cookie_string = f"Cookie: {';'.join(cookies)}"
            if not self.args.get('headers'):
                self.args['headers'] = []
            self.args['headers'].append(cookie_string)
```
Which works in most cases but breaks in case of redirection. I think this code path should only be used for code path when you test injection in cookie itself. Otherwise it should be send as cookie using requests cookies parameter. Unless you want to disable redirects and handle them manually ?

**Comment by vladko312** [comment]
I would probably rewrite this part.

**Comment by vladko312** [comment]
Should work fine in 1.1.2
Can you confirm?

**Comment by sectroyer** [comment]
Yes it now works as expected 👍
