### ISSUE TITLE
ModuleNotFoundError: No module named 'mechanize'

### ISSUE THREAD

**Issue by jedai47** [vladko312/SSTImap#25]
`pip3.11 install -r requirements.txt
Collecting argparse~=1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting requests~=2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: urllib3~=1.26.9 in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.26.16)
Collecting mechanize~=0.4.8
  Using cached mechanize-0.4.8-py2.py3-none-any.whl (110 kB)
Collecting html5lib~=1.1
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests~=2.27.1->-r requirements.txt (line 2)) (2022.12.7)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests~=2.27.1->-r requirements.txt (line 2)) (2.8)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.11/site-packages (from html5lib~=1.1->-r requirements.txt (line 5)) (1.16.0)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, argparse, html5lib, charset-normalizer, requests, mechanize
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.1.0
    Uninstalling charset-normalizer-3.1.0:
      Successfully uninstalled charset-normalizer-3.1.0
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
Successfully installed argparse-1.4.0 charset-normalizer-2.0.12 html5lib-1.1 mechanize-0.4.8 requests-2.27.1 webencodings-0.5.1

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: /usr/local/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
macpro@192.168.1.21@/Users/macpro/SSTImap {SSTImap $ python3.11 sstimap.py
Traceback (most recent call last):
  File "/Users/macpro/SSTImap/sstimap.py", line 10, in <module>
    from utils import cliparser
  File "/Users/macpro/SSTImap/utils/cliparser.py", line 2, in <module>
    from sstimap import version
  File "/Users/macpro/SSTImap/sstimap.py", line 11, in <module>
    from core import checks
  File "/Users/macpro/SSTImap/core/checks.py", line 10, in <module>
    from utils.crawler import crawl, find_forms
  File "/Users/macpro/SSTImap/utils/crawler.py", line 13, in <module>
    from mechanize._form import parse_forms
ModuleNotFoundError: No module named 'mechanize'`

**Comment by vladko312** [comment]
Seems like there is a problem with your Python. Can you import `mechanize` in pure Python? Can you import other modules?

**Comment by AltoPalo** [comment]
exactly the same issues for me :/

**Comment by vladko312** [comment]
Have you installed python libraries using `sudo` or `--user`?
Can you just do `import mechanize` in python?

**Comment by vladko312** [comment]
Closing for now, as no confirmation was given.
Seema like an issue with your module installation path, not SSTImap
