### ISSUE TITLE
为什么在运行时会出现乱码

### ISSUE THREAD

**Issue by wushangyu** [vladko312/SSTImap#36]
![PixPin_2024-03-24_21-24-31](https://github.com/vladko312/SSTImap/assets/99347371/5d85e48b-e5d2-4ac7-9757-841357d727c6)

**Comment by vladko312** [comment]
I will add support for removing color soon. 
For Windows, I would recommend downloading **Windows Terminal** app from Microsoft store to get color support.

**Comment by vladko312** [comment]
Try using `--no-color` option, should work now.

**Comment by vladko312** [comment]
It works now, but no confirmation was given for a long time.
