### ISSUE TITLE
Used in multiple pages

### ISSUE THREAD

**Issue by 1Martinik** [vladko312/SSTImap#42]
Hi,
Is it possible to inject payloads in "test.local/page1" and then check the reflected results in "test.local/page2"? 
This is useful in case we have the "test.local/page1" where we make a POST request to change a field value and the change is visible in a different page "test.local/page2" when we make a GET request.
Thank you.

**Comment by vladko312** [comment]
Currently, SSTImap doesn't support second order URLs, as was mentioned in issue #12 

This would be added in a future update.
